"""Added relationships between models

Revision ID: 8be3026b664f
Revises: 9e1dc43829d7
Create Date: 2024-10-17 09:45:38.738613

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8be3026b664f'
down_revision = '9e1dc43829d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('current_price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('market_cap',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.alter_column('market_cap',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('current_price',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
